In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
mnist = tf.keras.datasets.mnist

In [4]:
mnist

<module 'tensorflow.keras.datasets.mnist' from '/home/garbade/.pyenv/versions/3.8.5/envs/py38_venv/lib/python3.8/site-packages/tensorflow/keras/datasets/mnist/__init__.py'>

In [5]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [6]:
x_train.shape

(60000, 28, 28)

In [7]:
y_train.shape

(60000,)

In [17]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [18]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [25]:
predictions = model(x_train[:1]).numpy()

In [26]:
predictions

array([[ -34.952023 ,  -25.508156 ,  -15.971821 ,   -4.3515396,
         191.08061  , -220.16077  ,  169.44577  ,  217.29466  ,
         306.0382   ,   36.90896  ]], dtype=float32)

In [27]:
tf.nn.softmax(predictions).numpy()

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)

In [28]:
predictions.shape

(1, 10)

In [29]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [30]:
loss_fn(y_train[:1], predictions).numpy()

526.199

In [31]:
y_train[:1]

array([5], dtype=uint8)

In [32]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [33]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 560us/step - loss: 2.6278 - accuracy: 0.7588
Epoch 2/5
1875/1875 [==============================] - 1s 564us/step - loss: 0.5554 - accuracy: 0.8501
Epoch 3/5
1875/1875 [==============================] - 1s 580us/step - loss: 0.4824 - accuracy: 0.8711
Epoch 4/5
1875/1875 [==============================] - 1s 549us/step - loss: 0.4307 - accuracy: 0.8874
Epoch 5/5
1875/1875 [==============================] - 1s 541us/step - loss: 0.4000 - accuracy: 0.8970


In [34]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.2900 - accuracy: 0.9353


[0.28996315598487854, 0.9352999925613403]

In [35]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])


In [40]:
result = probability_model(x_test[:5])
result

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.0000000e+00, 1.1411184e-20, 5.9702100e-21, 1.0664795e-12,
        0.0000000e+00, 3.5305979e-37, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 5.3598339e-21],
       [2.4809996e-20, 6.1925022e-07, 9.9999940e-01, 6.0449286e-09,
        1.1970752e-23, 6.3278610e-23, 4.9700734e-12, 2.9841706e-23,
        4.9310113e-19, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 1.6742257e-14, 7.1645602e-30,
        7.4393709e-15, 2.0593946e-15, 4.4405334e-18, 3.1934076e-12,
        2.7874214e-13, 4.4583658e-21],
       [9.9999416e-01, 8.2622348e-32, 4.7409355e-07, 9.9531352e-15,
        2.4745075e-16, 7.4889233e-09, 1.0939659e-07, 5.2259452e-06,
        7.6812851e-13, 2.9776993e-21],
       [3.8966304e-05, 2.9794736e-08, 1.1187497e-06, 6.0079952e-10,
        9.9988139e-01, 1.4387350e-06, 5.2880472e-07, 5.0470888e-05,
        1.8801649e-06, 2.4063886e-05]], dtype=float32)>

In [38]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [41]:
import numpy as np

In [47]:
result.numpy().argmax(axis=1)

array([7, 2, 1, 0, 4])